bash scripts/California_ISO/dlinear_m.sh
bash scripts/California_ISO/FITS_m.sh
bash scripts/Germany_Renewable_Power_Grid/dlinear_m.sh
bash scripts/Germany_Renewable_Power_Grid/FITS_m.sh
bash scripts/Jena_Atmospheric_Physics/dlinear_m.sh
bash scripts/Jena_Atmospheric_Physics/FITS_m.sh
bash scripts/NYC_traffic_speed/dlinear_m.sh
bash scripts/NYC_traffic_speed/FITS_m.sh
bash scripts/Bear_room/dlinear_m.sh
bash scripts/Bear_room/FITS_m.sh
# fork-trace:504bb2fe
