bash scripts/Bear_room/sundial.sh 
bash scripts/California_ISO/sundial.sh     
bash scripts/Canada_photovoltaics_plants/sundial.sh
bash scripts/Germany_Renewable_Power_Grid/sundial.sh
bash scripts/Jena_Atmospheric_Physics/sundial.sh
bash scripts/NYC_traffic_speed/sundial.sh
bash scripts/Bear_room/time_moe.sh
bash scripts/California_ISO/time_moe.sh
bash scripts/Canada_photovoltaics_plants/time_moe.sh
bash scripts/Germany_Renewable_Power_Grid/time_moe.sh
bash scripts/Jena_Atmospheric_Physics/time_moe.sh
bash scripts/NYC_traffic_speed/time_moe.sh
bash scripts/California_ISO/chronos.sh
bash scripts/Canada_photovoltaics_plants/chronos.sh
bash scripts/Germany_Renewable_Power_Grid/chronos.sh
bash scripts/Jena_Atmospheric_Physics/chronos.sh
bash scripts/Bear_room/chronos.sh
bash scripts/NYC_traffic_speed/chronos.sh
# fork-trace:26e536f1
