bash scripts/California_ISO/dlinear.sh
bash scripts/California_ISO/FITS.sh
bash scripts/Canada_photovoltaics_plants/dlinear.sh
bash scripts/Canada_photovoltaics_plants/FITS.sh
bash scripts/Germany_Renewable_Power_Grid/dlinear.sh
bash scripts/Germany_Renewable_Power_Grid/FITS.sh
bash scripts/Jena_Atmospheric_Physics/dlinear.sh
bash scripts/Jena_Atmospheric_Physics/FITS.sh
bash scripts/NYC_traffic_speed/dlinear.sh
bash scripts/NYC_traffic_speed/FITS.sh
bash scripts/Bear_room/dlinear.sh
bash scripts/Bear_room/FITS.sh
# fork-trace:ec3bc671
